### ISSUE TITLE
Not working on Video.js 5.10.4

### ISSUE THREAD

**Issue by sumiitmalik** [ryanpatrickcook/videojs-wistia#1]
Uncaught TypeError: Cannot read property 'extend' of undefined
VIDEOJS: ERROR: The "Wistia" tech is undefined. Skipped browser support check for that tech.

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. i {code: 4, message: "No compatible source was found for this media."}code: 4message: "No compatible source was found for this media."**proto**: Objecte @ log.js:77h.error @ log.js:29b.error @ player.js:2244(anonymous function) @ player.js:1966e @ fn.js:35

Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

**Comment by ryanpatrickcook** [comment]
I've just updated the tech to support Video.js 5. You can find an example here using 5.10.7: http://ryanpatrickcook.github.io/videojs-wistia/

Closed via https://github.com/ryanpatrickcook/videojs-wistia/pull/2
