### ISSUE TITLE
Hide Wistia controls?

### ISSUE THREAD

**Issue by samhibberd** [ryanpatrickcook/videojs-wistia#5]
Is it possible to hide the native Wistia controls and use only the videojs controls?

**Comment by ryanpatrickcook** [comment]
Yeah, that should be doable. I'll check into this over the next day and push an update to the project. Thanks!

**Comment by ryanpatrickcook** [comment]
I pushed up a fix that should allow you do this. The last video on the [example page](http://ryanpatrickcook.github.io/videojs-wistia/) will show you how to implement.

If you grab the new source and try to implement the below it should work for you.

You'll need to setup your `video` tag with the `controls` attribute to allow video.js controls.
```html
<video id="vid3" src="" class="video-js vjs-default-skin" controls preload="auto" width="640" height="360">
  <p>Video Playback Not Supported</p>
</video>
```

and then when you initialize your video, your wistia url should include the `chromeless` param.
```javascript
videojs('vid3', {
  "techOrder": ["wistia"],
  "sources": [{
    "type": "video/wistia",
    "src": "https://home.wistia.com/medias/oefj398m6q?chromeless=true"
  }]
})
```

Closed via https://github.com/ryanpatrickcook/videojs-wistia/pull/6

**Comment by samhibberd** [comment]
Brilliant!!! Works perfectly! Thanks.
